# Generated by Django 5.2.5 on 2025-09-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('key', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Für wen ist dieses Token? (z. B.: Klasse 10, Batch-A)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Ist dieses Token derzeit aktiv?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
