# Generated by Django 5.2.5 on 2025-09-06 16:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='description',
            field=models.CharField(blank=True, help_text='Für wen ist dieses Token? (z. B.: Klasse 10, Batch-A)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='key',
            field=models.CharField(default=users.models.generate_unique_token, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
