# Generated by Django 5.2.5 on 2025-09-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
