# Generated by Django 5.2.5 on 2025-09-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_subject_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
