# Generated by Django 5.2.5 on 2025-09-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questions.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='questions.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='questions.subject'),
            preserve_default=False,
        ),
    ]
