# Generated by Django 5.2.5 on 2025-09-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_category_group_subcategory_group_subcategory_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category', 'name', 'subject', 'group'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('subject', 'name', 'group')},
        ),
    ]
