# Generated by Django 5.2.5 on 2025-09-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name', 'category', 'subject', 'group'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'subject', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category', 'subject', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'group')},
        ),
    ]
