# Generated by Django 5.2.5 on 2025-10-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['group'], name='q_group_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject'], name='q_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='q_category_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(condition=models.Q(('subcategory__isnull', False)), fields=['subcategory'], name='q_subcat_partial_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['level', 'type'], name='q_level_type_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='q_created_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['group', 'subject', 'category'], name='question_gsc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['group', 'subject'], name='question_gs_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'category'], name='question_sc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['level'], name='q_level_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='q_type_idx'),
        ),
    ]
