# docker-compose.yml

version: '3.8'

services:
  # The PostgreSQL Database Service
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The Django App Service (Gunicorn)
  app:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  # The Nginx Reverse Proxy Service
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "8091:80" # Map host port 8090 to container port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: